### PR TITLE
Update privacy notice

### PR DESCRIPTION
**Pull request by InezMc**
Add line "We will never reactivate an account for you which has been deleted."

### CODE REVIEW

**Comment by aaronraimist** [comment]
Shouldn't this say "which has been deactivated"?

**Review by deniseal — APPROVED** [review]
Have changed 'deleted' to 'deactivated'. Approved.

**Review by AmandineLP — COMMENTED** [review]
Really?

**Comment by InezMc** [comment]
It is currently not technically possible for m.org users to be reactivated once they have been deactivated.

**Comment by AmandineLP** [comment]
In that case shouldn't be saying "We can not reactivate"? the current wording make it sound like we don't want to.

**Comment by aaronraimist** [comment]
> It is currently not technically possible for m.org users to be reactivated once they have been deactivated.

matrix.org has a policy not to reactivate accounts but that is just a policy. There is no technical barrier to reactivating accounts. Here's the API to do it https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account.

AIUI the reason for the policy is because deactivating the account deletes things like attached email addresses or phone numbers which would allow matrix.org support to determine if you really had been the owner of the account before it was deactivated.

**Comment by deniseal** [comment]
Closing this as it is addressed by a more recent PR (https://github.com/vector-im/policies/pull/44), which includes the feedback by @AmandineLP and @aaronraimist

**Pull request closed without merging**
